/**
 * Send Invoice Email Edge Function
 * 
 * Sends an invoice email to parent/guardian with invoice details.
 * 
 * Expected body: { invoice_id, recipient_email? }
 * Auth: Bearer token required
 */

import { serve } from 'https://deno.land/std@0.214.0/http/server.ts';
import { createClient } from 'npm:@supabase/supabase-js@2';
import { getCorsHeaders, handleCorsOptions } from '../_shared/cors.ts';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') || '';
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

if (!SUPABASE_SERVICE_ROLE_KEY) {
  throw new Error('SUPABASE_SERVICE_ROLE_KEY is required');
}

serve(async (req: Request) => {
  const corsHeaders = getCorsHeaders(req);
  if (req.method === 'OPTIONS') return handleCorsOptions(req);

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY!);
    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    if (authError || !user) {
      return new Response(JSON.stringify({ error: 'Invalid session' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const body = await req.json();
    const { invoice_id, recipient_email } = body;

    if (!invoice_id) {
      return new Response(JSON.stringify({ error: 'Missing invoice_id' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Fetch invoice
    const { data: invoice, error: invoiceErr } = await supabase
      .from('invoices')
      .select('*, students(first_name, last_name), profiles!invoices_parent_id_fkey(first_name, last_name, email)')
      .eq('id', invoice_id)
      .single();

    if (invoiceErr || !invoice) {
      return new Response(JSON.stringify({ error: 'Invoice not found' }), {
        status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const toEmail = recipient_email || (invoice as any).profiles?.email;
    if (!toEmail) {
      return new Response(JSON.stringify({ error: 'No recipient email' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const parentName = `${(invoice as any).profiles?.first_name || ''} ${(invoice as any).profiles?.last_name || ''}`.trim() || 'Parent';
    const studentName = `${(invoice as any).students?.first_name || ''} ${(invoice as any).students?.last_name || ''}`.trim() || 'Student';
    const amount = Number(invoice.total_amount || invoice.amount || 0).toFixed(2);

    const emailBody = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #1e3a5f;">Invoice from EduDash Pro</h2>
        <p>Dear ${parentName},</p>
        <p>Please find your invoice details below:</p>
        <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
          <tr style="background: #f8f9fa;">
            <td style="padding: 8px; border: 1px solid #dee2e6;"><strong>Invoice #</strong></td>
            <td style="padding: 8px; border: 1px solid #dee2e6;">${invoice.invoice_number || invoice_id}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #dee2e6;"><strong>Student</strong></td>
            <td style="padding: 8px; border: 1px solid #dee2e6;">${studentName}</td>
          </tr>
          <tr style="background: #f8f9fa;">
            <td style="padding: 8px; border: 1px solid #dee2e6;"><strong>Amount Due</strong></td>
            <td style="padding: 8px; border: 1px solid #dee2e6;"><strong>R ${amount}</strong></td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #dee2e6;"><strong>Due Date</strong></td>
            <td style="padding: 8px; border: 1px solid #dee2e6;">${invoice.due_date || 'Upon receipt'}</td>
          </tr>
          <tr style="background: #f8f9fa;">
            <td style="padding: 8px; border: 1px solid #dee2e6;"><strong>Status</strong></td>
            <td style="padding: 8px; border: 1px solid #dee2e6;">${invoice.status || 'pending'}</td>
          </tr>
        </table>
        ${invoice.description ? `<p><strong>Description:</strong> ${invoice.description}</p>` : ''}
        <p style="color: #64748b; font-size: 12px;">This invoice was generated by EduDash Pro. For questions, please contact your school.</p>
      </div>
    `;

    // Send via send-email Edge Function
    await supabase.functions.invoke('send-email', {
      body: {
        to: toEmail,
        subject: `Invoice ${invoice.invoice_number || ''} — R ${amount} — ${studentName}`,
        body: emailBody,
        is_html: true,
        confirmed: true,
      },
    });

    console.log('[send-invoice-email] Sent:', { invoice_id, to: toEmail });

    return new Response(JSON.stringify({ success: true }), {
      status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (err) {
    console.error('[send-invoice-email] Error:', err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    );
  }
});
