/**
 * Styles for Budget Requests Screen
 */
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 16 },
  loadingText: { fontSize: 16 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, gap: 12 },
  backButton: { padding: 4 },
  headerTitleContainer: { flex: 1 },
  headerTitle: { fontSize: 20, fontWeight: '700' },
  headerSubtitle: { fontSize: 12, marginTop: 2 },
  addButton: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  statsContainer: { flexDirection: 'row', paddingHorizontal: 16, marginTop: 12, gap: 8 },
  statCard: { flex: 1, alignItems: 'center', padding: 12, borderRadius: 12, gap: 4 },
  statCardValue: { fontSize: 20, fontWeight: '700' },
  statCardLabel: { fontSize: 11 },
  filtersContainer: { marginTop: 12 },
  filtersList: { paddingHorizontal: 16 },
  filterChip: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, borderWidth: 1, marginRight: 8 },
  filterText: { fontSize: 14, fontWeight: '500' },
  listContent: { padding: 16, flexGrow: 1 },
  requestCard: { padding: 16, borderRadius: 12 },
  requestHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
  requestHeaderLeft: { flex: 1, gap: 6 },
  requestTitle: { fontSize: 16, fontWeight: '600' },
  categoryBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  categoryText: { fontSize: 11, fontWeight: '500' },
  statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, gap: 4 },
  statusText: { fontSize: 11, fontWeight: '600' },
  amountContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 12, gap: 8 },
  amountLabel: { fontSize: 14 },
  amountValue: { fontSize: 18, fontWeight: '700' },
  requestDescription: { fontSize: 14, lineHeight: 20, marginTop: 8 },
  requestFooter: { flexDirection: 'row', marginTop: 12, gap: 16 },
  footerItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  footerText: { fontSize: 12 },
  notesContainer: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 12, padding: 10, borderRadius: 8, gap: 8 },
  notesText: { flex: 1, fontSize: 12, lineHeight: 18 },
  separator: { height: 12 },
  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 48 },
  emptyTitle: { fontSize: 18, fontWeight: '600', marginTop: 16 },
  emptyText: { fontSize: 14, textAlign: 'center', marginTop: 8 },
  // Modal styles
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingTop: 20, paddingHorizontal: 20, paddingBottom: 40, maxHeight: '90%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: '700' },
  modalForm: { maxHeight: 400 },
  inputLabel: { fontSize: 14, fontWeight: '600', marginBottom: 8, marginTop: 16 },
  textInput: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, fontSize: 16 },
  textArea: { height: 100, paddingTop: 12 },
  categorySelector: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  categoryOption: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, borderWidth: 1 },
  categoryOptionText: { fontSize: 14, fontWeight: '500' },
  submitButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#10B981', paddingVertical: 14, borderRadius: 12, marginTop: 20, gap: 8 },
  submitButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
});
