/**
 * Styles for Pending Approvals Screen
 */
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 16 },
  loadingText: { fontSize: 16 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, gap: 12 },
  backButton: { padding: 4 },
  headerTitleContainer: { flex: 1 },
  headerTitle: { fontSize: 20, fontWeight: '700' },
  headerSubtitle: { fontSize: 12, marginTop: 2 },
  statsBar: { flexDirection: 'row', marginHorizontal: 16, marginTop: 8, padding: 12, borderRadius: 12, gap: 16 },
  statItem: { flex: 1, alignItems: 'center' },
  statNumber: { fontSize: 24, fontWeight: '700' },
  statLabel: { fontSize: 11, marginTop: 2 },
  tabsContainer: { marginTop: 16 },
  tabsList: { paddingHorizontal: 16 },
  tab: { paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20, marginRight: 8 },
  tabText: { fontSize: 14, fontWeight: '600' },
  listContent: { padding: 16, paddingBottom: 100, flexGrow: 1 },
  approvalCard: { padding: 16, borderRadius: 12 },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  typeIconContainer: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  cardHeaderText: { flex: 1 },
  requestTitle: { fontSize: 16, fontWeight: '600' },
  requestMeta: { flexDirection: 'row', alignItems: 'center', marginTop: 4, gap: 8 },
  metaDot: { width: 4, height: 4, borderRadius: 2 },
  requestMetaText: { fontSize: 12 },
  urgentBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, gap: 4 },
  urgentText: { fontSize: 11, fontWeight: '600' },
  requestDescription: { fontSize: 14, lineHeight: 20, marginTop: 12 },
  requestDetails: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 12, gap: 12 },
  detailItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  detailText: { fontSize: 13 },
  amountHighlight: { fontWeight: '700' },
  actionButtons: { flexDirection: 'row', marginTop: 16, gap: 12 },
  actionButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderRadius: 10, gap: 6 },
  rejectButton: { backgroundColor: '#FEE2E2' },
  approveButton: { backgroundColor: '#D1FAE5' },
  actionButtonText: { fontSize: 14, fontWeight: '600' },
  historyInfo: { flexDirection: 'row', alignItems: 'center', marginTop: 12, paddingTop: 12, borderTopWidth: 1, gap: 8 },
  historyText: { fontSize: 12 },
  statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, gap: 4 },
  statusText: { fontSize: 11, fontWeight: '600' },
  separator: { height: 12 },
  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 48 },
  emptyTitle: { fontSize: 18, fontWeight: '600', marginTop: 16 },
  emptyText: { fontSize: 14, textAlign: 'center', marginTop: 8 },
});
