/**
 * Styles for Youth Programs Screen
 */
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 16 },
  loadingText: { fontSize: 16 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, gap: 12 },
  backButton: { padding: 4 },
  headerTitleContainer: { flex: 1 },
  headerTitle: { fontSize: 20, fontWeight: '700' },
  headerSubtitle: { fontSize: 12, marginTop: 2 },
  addButton: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  statsContainer: { flexDirection: 'row', paddingHorizontal: 16, marginTop: 12, gap: 8 },
  statCard: { flex: 1, alignItems: 'center', padding: 12, borderRadius: 12, gap: 4 },
  statCardValue: { fontSize: 18, fontWeight: '700' },
  statCardLabel: { fontSize: 11 },
  searchContainer: { flexDirection: 'row', alignItems: 'center', marginHorizontal: 16, marginTop: 12, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12, gap: 8 },
  searchInput: { flex: 1, fontSize: 16, padding: 0 },
  filtersContainer: { marginTop: 12 },
  filtersList: { paddingHorizontal: 16, gap: 8 },
  filterChip: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, borderWidth: 1, marginRight: 8 },
  filterText: { fontSize: 14, fontWeight: '500' },
  listContent: { padding: 16, flexGrow: 1 },
  programCard: { padding: 16, borderRadius: 12 },
  programHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  categoryIcon: { width: 48, height: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  programHeaderText: { flex: 1 },
  programName: { fontSize: 16, fontWeight: '600' },
  programCategory: { fontSize: 12, marginTop: 2 },
  statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, gap: 4 },
  statusText: { fontSize: 11, fontWeight: '600' },
  programDescription: { fontSize: 14, lineHeight: 20, marginTop: 12 },
  programStats: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 12, gap: 16 },
  statItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  statText: { fontSize: 12 },
  separator: { height: 12 },
  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 48 },
  emptyTitle: { fontSize: 18, fontWeight: '600', marginTop: 16 },
  emptyText: { fontSize: 14, textAlign: 'center', marginTop: 8, marginHorizontal: 32 },
  createButton: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 12, borderRadius: 24, marginTop: 20, gap: 8 },
  createButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
});
