/**
 * Styles for Youth Reports Screen
 */
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 16 },
  loadingText: { fontSize: 16 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, gap: 12 },
  backButton: { padding: 4 },
  headerTitleContainer: { flex: 1 },
  headerTitle: { fontSize: 20, fontWeight: '700' },
  headerSubtitle: { fontSize: 12, marginTop: 2 },
  exportButton: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  periodSelector: { flexDirection: 'row', paddingHorizontal: 16, marginTop: 12, gap: 8 },
  periodOption: { flex: 1, paddingVertical: 10, borderRadius: 8, alignItems: 'center' },
  periodText: { fontSize: 14, fontWeight: '600' },
  scrollContent: { padding: 16, paddingBottom: 32 },
  sectionCard: { padding: 16, borderRadius: 16, marginBottom: 16 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16 },
  sectionIcon: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  sectionTitle: { fontSize: 18, fontWeight: '700' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  statItem: { width: '50%', paddingVertical: 8 },
  statValue: { fontSize: 24, fontWeight: '700' },
  statLabel: { fontSize: 12, marginTop: 2 },
  ratingContainer: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  progressContainer: { marginTop: 16 },
  progressBar: { height: 8, borderRadius: 4, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 4 },
  progressText: { fontSize: 12, marginTop: 6, textAlign: 'center' },
  chartContainer: { paddingTop: 8 },
  chartTitle: { fontSize: 16, fontWeight: '600', marginBottom: 16 },
  barChart: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', height: 150, paddingTop: 20 },
  barItem: { alignItems: 'center', flex: 1 },
  barWrapper: { height: 120, justifyContent: 'flex-end' },
  bar: { width: 32, borderRadius: 4, minHeight: 4 },
  barLabel: { fontSize: 11, marginTop: 8 },
  quickActions: { flexDirection: 'row', gap: 12, marginTop: 8 },
  actionButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 16, borderRadius: 12, gap: 8 },
  actionText: { fontSize: 14, fontWeight: '600' },
});
