import { DashPDFGenerator } from '@/services/DashPDFGenerator';
import { assertSupabase } from '@/lib/supabase';
import { SchoolSettingsService } from '@/lib/services/SchoolSettingsService';

export interface ReceiptFeeDetails {
  id: string;
  description: string;
  amount: number;
  dueDate?: string | null;
  paidDate: string;
  paymentReference: string;
  paymentMethod: string;
}

export interface ReceiptStudentDetails {
  id: string;
  firstName: string;
  lastName: string;
  className?: string | null;
}

export interface ReceiptParentDetails {
  id?: string | null;
  name?: string | null;
  email?: string | null;
}

export interface ReceiptIssuerDetails {
  id: string;
  name: string;
}

export interface ReceiptGenerationRequest {
  schoolId: string;
  fee: ReceiptFeeDetails;
  student: ReceiptStudentDetails;
  parent?: ReceiptParentDetails;
  issuer: ReceiptIssuerDetails;
}

export interface ReceiptGenerationResult {
  storagePath?: string;
  receiptUrl?: string | null;
  filename?: string;
}

const escapeHtml = (value: string): string => {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
};

const formatCurrency = (amount: number): string => `R ${amount.toFixed(2)}`;

const formatDate = (dateString?: string | null): string => {
  if (!dateString) return '—';
  const date = new Date(dateString);
  if (Number.isNaN(date.getTime())) return '—';
  return date.toLocaleDateString('en-ZA', { day: '2-digit', month: 'short', year: 'numeric' });
};

export class ReceiptService {
  static async generateFeeReceipt(request: ReceiptGenerationRequest): Promise<ReceiptGenerationResult> {
    const supabase = assertSupabase();
    const settings = await SchoolSettingsService.get(request.schoolId);
    const schoolName = settings.schoolName || 'School';
    const primaryColor = settings.primaryColor || '#1F5EFF';
    const accentColor = settings.secondaryColor || '#64748B';
    const logoUri = settings.schoolLogo;

    const receiptNumber = `REC-${new Date().getFullYear()}-${request.fee.id.slice(0, 6).toUpperCase()}`;
    const studentName = `${request.student.firstName} ${request.student.lastName}`.trim();
    const parentName = request.parent?.name || '—';

    const headerHtmlSafe = `
      <div style="display:flex; align-items:center; justify-content:space-between; padding-bottom:16px; border-bottom:1px solid #E5E7EB;">
        <div style="display:flex; align-items:center; gap:12px;">
          ${
            logoUri
              ? `<img src="${logoUri}" alt="${escapeHtml(schoolName)} logo" style="height:48px; width:auto; border-radius:10px;" />`
              : `<div style="width:48px; height:48px; border-radius:12px; background:${primaryColor}20; display:flex; align-items:center; justify-content:center; color:${primaryColor}; font-weight:700; font-size:18px;">
                   ${escapeHtml(schoolName.slice(0, 1).toUpperCase())}
                 </div>`
          }
          <div>
            <div style="font-size:18px; font-weight:700; color:#0F172A;">${escapeHtml(schoolName)}</div>
            <div style="font-size:12px; color:#64748B;">Payment Receipt</div>
          </div>
        </div>
        <div style="text-align:right; font-size:12px; color:#64748B;">
          <div>Receipt #${escapeHtml(receiptNumber)}</div>
          <div>${escapeHtml(formatDate(request.fee.paidDate))}</div>
        </div>
      </div>
    `;

    const footerHtmlSafe = `
      <div style="font-size:11px; color:#94A3B8; text-align:center;">
        Generated by EduDash Pro • ${escapeHtml(schoolName)}
      </div>
    `;

    const receiptHtml = `
      <div style="margin-top:18px;">
        <div style="display:flex; justify-content:space-between; gap:24px; margin-bottom:18px;">
          <div style="flex:1; background:#F8FAFC; padding:12px; border-radius:12px; border:1px solid #E2E8F0;">
            <div style="font-size:12px; text-transform:uppercase; letter-spacing:0.06em; color:#64748B; margin-bottom:6px;">Student</div>
            <div style="font-size:15px; font-weight:600; color:#0F172A;">${escapeHtml(studentName)}</div>
            <div style="font-size:12px; color:#64748B;">Class: ${escapeHtml(request.student.className || '—')}</div>
          </div>
          <div style="flex:1; background:#F8FAFC; padding:12px; border-radius:12px; border:1px solid #E2E8F0;">
            <div style="font-size:12px; text-transform:uppercase; letter-spacing:0.06em; color:#64748B; margin-bottom:6px;">Parent / Guardian</div>
            <div style="font-size:15px; font-weight:600; color:#0F172A;">${escapeHtml(parentName)}</div>
            <div style="font-size:12px; color:#64748B;">${escapeHtml(request.parent?.email || '—')}</div>
          </div>
        </div>

        <table style="width:100%; border-collapse:collapse; font-size:13px;">
          <thead>
            <tr style="background:${primaryColor}15;">
              <th style="text-align:left; padding:10px; border-bottom:1px solid #E2E8F0;">Description</th>
              <th style="text-align:left; padding:10px; border-bottom:1px solid #E2E8F0;">Due Date</th>
              <th style="text-align:left; padding:10px; border-bottom:1px solid #E2E8F0;">Paid Date</th>
              <th style="text-align:right; padding:10px; border-bottom:1px solid #E2E8F0;">Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style="padding:10px; border-bottom:1px solid #E2E8F0;">${escapeHtml(request.fee.description)}</td>
              <td style="padding:10px; border-bottom:1px solid #E2E8F0;">${escapeHtml(formatDate(request.fee.dueDate))}</td>
              <td style="padding:10px; border-bottom:1px solid #E2E8F0;">${escapeHtml(formatDate(request.fee.paidDate))}</td>
              <td style="padding:10px; text-align:right; border-bottom:1px solid #E2E8F0; font-weight:600;">${escapeHtml(formatCurrency(request.fee.amount))}</td>
            </tr>
          </tbody>
        </table>

        <div style="display:flex; justify-content:space-between; margin-top:18px;">
          <div style="font-size:12px; color:#64748B;">
            <div>Payment method: ${escapeHtml(request.fee.paymentMethod)}</div>
            <div>Reference: ${escapeHtml(request.fee.paymentReference)}</div>
          </div>
          <div style="text-align:right;">
            <div style="font-size:12px; color:#64748B; margin-bottom:4px;">Total Paid</div>
            <div style="font-size:20px; font-weight:700; color:${primaryColor};">${escapeHtml(formatCurrency(request.fee.amount))}</div>
          </div>
        </div>

        <div style="margin-top:20px; font-size:12px; color:#64748B;">
          Issued by: ${escapeHtml(request.issuer.name)}
        </div>
      </div>
    `;

    const generator = DashPDFGenerator.getInstance();
    const result = await generator.generateFromStructuredData({
      type: 'invoice',
      title: `${schoolName} Receipt`,
      sections: [
        {
          id: 'receipt-details',
          title: 'Receipt Details',
          markdown: receiptHtml.replace(/\n/g, ''),
        },
      ],
      preferencesOverride: {
        theme: 'professional',
        branding: {
          logoUri,
          primaryColor,
          secondaryColor: accentColor,
          headerHtmlSafe,
          footerHtmlSafe,
        },
      },
    });

    if (!result.success) {
      throw new Error(result.error || 'Receipt generation failed');
    }

    if (!result.storagePath) {
      return {
        storagePath: undefined,
        receiptUrl: null,
        filename: result.filename,
      };
    }

    const { data: signed } = await supabase.storage
      .from('generated-pdfs')
      .createSignedUrl(result.storagePath, 60 * 60 * 24 * 365);

    if (result.storagePath) {
      const receiptRow = {
        document_type: 'receipt',
        filename: result.filename || `receipt-${receiptNumber}.pdf`,
        storage_path: result.storagePath,
        title: `Receipt - ${studentName}`,
        user_id: request.issuer.id,
        preschool_id: request.schoolId,
        organization_id: request.schoolId,
        metadata: {
          student_id: request.student.id,
          fee_id: request.fee.id,
          payment_reference: request.fee.paymentReference,
          receipt_number: receiptNumber,
          document_subtype: 'receipt',
        },
      } as const;

      const { error: receiptInsertError } = await supabase
        .from('pdf_documents')
        .insert(receiptRow);

      if (receiptInsertError) {
        console.warn('[ReceiptService] pdf_documents insert failed, retrying as invoice:', receiptInsertError.message);
        await supabase.from('pdf_documents').insert({
          ...receiptRow,
          document_type: 'invoice',
        });
      }
    }

    return {
      storagePath: result.storagePath,
      receiptUrl: signed?.signedUrl ?? null,
      filename: result.filename,
    };
  }
}
