import { StyleSheet } from 'react-native';
import { ThemeColors } from '@/contexts/ThemeContext';

export const createRegistrationStyles = (theme: ThemeColors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.background },
  content: { flexGrow: 1, padding: 16, gap: 12, paddingBottom: 32 },
  label: { color: theme.text, fontWeight: '600', marginTop: 6 },
  input: { backgroundColor: theme.surface, borderRadius: 10, padding: 12, color: theme.text, borderWidth: 1, borderColor: theme.border },
  inputError: { borderColor: theme.error },
  hint: { color: theme.textSecondary, fontSize: 12, marginBottom: 4 },
  error: { color: theme.error, fontSize: 12, marginTop: 4 },
  section: { marginTop: 10, paddingTop: 12, borderTopWidth: 1, borderTopColor: theme.border },
  sectionTitle: { color: theme.text, fontWeight: '700', fontSize: 16, marginBottom: 8 },
  btn: { backgroundColor: theme.primary, padding: 14, borderRadius: 10, alignItems: 'center', marginTop: 16 },
  btnText: { color: theme.onPrimary, fontWeight: '800' },
  headerTint: { backgroundColor: theme.background },
  dateButton: {
    backgroundColor: theme.surface,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dateButtonText: {
    color: theme.text,
    fontSize: 16,
  },
  dateButtonPlaceholder: {
    color: theme.textSecondary,
    fontSize: 16,
  },
  genderRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  genderButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surface,
    alignItems: 'center',
  },
  genderButtonActive: {
    backgroundColor: theme.primary + '20',
    borderColor: theme.primary,
  },
  genderButtonText: {
    color: theme.text,
    fontWeight: '500',
  },
  genderButtonTextActive: {
    color: theme.primary,
    fontWeight: '600',
  },
  organizationContainer: {
    backgroundColor: theme.surface,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
    marginTop: 8,
  },
  organizationScrollContainer: {
    backgroundColor: theme.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    marginTop: 8,
    maxHeight: 300,
    padding: 8,
  },
  organizationOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1.5,
    borderColor: theme.border,
    backgroundColor: theme.surface,
  },
  organizationOptionActive: {
    backgroundColor: theme.primary + '15',
    borderColor: theme.primary,
    borderWidth: 2,
  },
  organizationName: {
    color: theme.text,
    fontWeight: '600',
    fontSize: 16,
  },
  organizationNameActive: {
    color: theme.primary,
    fontWeight: '700',
  },
});
