/**
 * Teacher Dashboard Styles
 */

import { StyleSheet } from 'react-native';
import { cardWidth, getScaledSize, getResponsivePadding } from './types';

export const getStyles = (theme: any, isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.background,
    },
    loadingText: {
      fontSize: 16,
      color: theme.textSecondary,
    },
    header: {
      backgroundColor: 'transparent',
      padding: 16,
    },
    headerCard: {
      backgroundColor: theme.cardBackground,
      borderRadius: getResponsivePadding(16),
      padding: getResponsivePadding(20),
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    headerContent: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    headerTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
    },
    subRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    roleBadge: {
      marginLeft: 8,
      backgroundColor: theme.primary + '10',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 999,
    },
    roleBadgeText: {
      color: theme.primary,
      fontSize: 10,
      fontWeight: '600',
      textTransform: 'capitalize',
    },
    greeting: {
      fontSize: getScaledSize(16),
      fontWeight: '600',
      color: theme.text,
      marginBottom: 4,
    },
    schoolName: {
      fontSize: getScaledSize(16),
      color: theme.textSecondary,
      fontWeight: '500',
    },
    section: {
      padding: getResponsivePadding(16),
    },
    sectionTitle: {
      fontSize: getScaledSize(18),
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: getResponsivePadding(16),
    },
    sectionCard: {
      backgroundColor: theme.cardBackground,
      borderRadius: 12,
      padding: 20,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    metricsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    metricCard: {
      backgroundColor: theme.cardBackground,
      borderRadius: getResponsivePadding(12),
      padding: getResponsivePadding(16),
      width: cardWidth,
      borderLeftWidth: 4,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    metricHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    metricValue: {
      fontSize: getScaledSize(24),
      fontWeight: 'bold',
      color: theme.text,
    },
    metricTitle: {
      fontSize: getScaledSize(14),
      fontWeight: '600',
      color: theme.text,
      marginBottom: 2,
    },
    metricSubtitle: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    quickActionsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    quickActionButton: {
      width: cardWidth,
      padding: getResponsivePadding(16),
      borderRadius: getResponsivePadding(12),
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: getScaledSize(80),
    },
    quickActionText: {
      color: theme.onPrimary || 'white',
      fontSize: getScaledSize(14),
      fontWeight: '600',
      marginTop: 8,
      textAlign: 'center',
    },
    aiToolsContainer: {
      gap: 12,
    },
    orgUsageRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    orgUsagePill: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: theme.cardBackground,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      color: theme.text,
      fontSize: 12,
      fontWeight: '600',
    },
    orgUsageLink: {
      color: theme.primary,
      fontWeight: '700',
      fontSize: 12,
    },
    upgradeNudge: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 12,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      backgroundColor: theme.cardBackground,
      marginBottom: 8,
    },
    upgradeNudgeText: {
      color: theme.text,
      fontSize: 13,
      fontWeight: '600',
    },
    upgradeNudgeLink: {
      color: theme.primary,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 4,
    },
    aiToolCard: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      borderRadius: 12,
      backgroundColor: theme.cardBackground,
    },
    aiToolIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 16,
    },
    aiToolContent: {
      flex: 1,
    },
    aiToolTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 2,
    },
    aiToolSubtitle: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    classesContainer: {
      gap: 12,
    },
    classCard: {
      backgroundColor: theme.cardBackground,
      borderRadius: 12,
      padding: 16,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    classHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    className: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 2,
    },
    classDetails: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    studentCount: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? theme.border + '40' : '#f1f5f9',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    studentCountText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textSecondary,
      marginLeft: 4,
    },
    nextLesson: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: isDark ? theme.border : '#f1f5f9',
    },
    nextLessonText: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.primary,
      marginLeft: 8,
    },
    attendanceInfo: {
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: isDark ? theme.border : '#f1f5f9',
    },
    attendanceBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
    },
    attendanceText: {
      fontSize: 12,
      fontWeight: '500',
      color: '#059669',
      marginLeft: 4,
    },
    attendanceRate: {
      fontSize: 11,
      color: theme.textSecondary,
      fontWeight: '500',
    },
    assignmentsContainer: {
      gap: 12,
    },
    assignmentCard: {
      backgroundColor: theme.cardBackground,
      borderRadius: 12,
      padding: 16,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    assignmentHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    assignmentTitle: {
      flex: 1,
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      marginRight: 12,
    },
    statusBadge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    statusText: {
      fontSize: 12,
      fontWeight: '600',
      color: 'white',
    },
    assignmentDue: {
      fontSize: 14,
      color: theme.textSecondary,
      marginBottom: 8,
    },
    assignmentProgress: {
      gap: 4,
    },
    progressText: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    progressBar: {
      height: 4,
      backgroundColor: isDark ? theme.border + '40' : '#f1f5f9',
      borderRadius: 2,
    },
    progressFill: {
      height: '100%',
      backgroundColor: theme.primary,
      borderRadius: 2,
    },
    eventItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? theme.border : '#f1f5f9',
    },
    eventIcon: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    eventContent: {
      flex: 1,
    },
    eventTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 2,
    },
    eventTime: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    modalContainer: {
      flex: 1,
      backgroundColor: theme.background,
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 24,
      paddingVertical: 20,
      paddingTop: 60,
      backgroundColor: theme.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.text,
    },
    modalCloseButton: {
      padding: 8,
      backgroundColor: theme.background,
      borderRadius: 8,
    },
    modalContent: {
      flex: 1,
    },
    loadingSkeleton: {
      padding: 16,
    },
    skeletonHeader: {
      height: 100,
      backgroundColor: isDark ? theme.border : '#E5E7EB',
      borderRadius: 16,
      marginBottom: 16,
    },
    skeletonMetrics: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      marginBottom: 16,
    },
    skeletonMetric: {
      width: cardWidth,
      height: 80,
      backgroundColor: isDark ? theme.border : '#E5E7EB',
      borderRadius: 12,
    },
    skeletonSection: {
      height: 200,
      backgroundColor: isDark ? theme.border : '#E5E7EB',
      borderRadius: 12,
    },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 32,
      backgroundColor: theme.background,
    },
    errorTitle: {
      fontSize: 20,
      fontWeight: '600',
      color: theme.error || '#DC2626',
      marginTop: 16,
      marginBottom: 8,
      textAlign: 'center',
    },
    errorText: {
      fontSize: 16,
      color: theme.textSecondary,
      textAlign: 'center',
      marginBottom: 24,
      lineHeight: 24,
    },
    retryButton: {
      backgroundColor: theme.primary,
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 8,
    },
    retryButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
    },
    headerMenuButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: isDark
        ? 'rgba(255, 255, 255, 0.1)'
        : 'rgba(75, 85, 99, 0.1)',
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    themeToggleButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.surfaceVariant || theme.surface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
      padding: 16,
    },
    upgradeModalContent: {
      backgroundColor: theme.cardBackground,
      borderRadius: 12,
      padding: 16,
      margin: 24,
      gap: 8,
    },
    optionsMenuContent: {
      backgroundColor: theme.cardBackground,
      borderRadius: 16,
      padding: 20,
      maxHeight: '80%',
    },
    optionsMenuHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    optionsMenuTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.text,
    },
    optionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    optionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    optionText: {
      marginLeft: 12,
      flex: 1,
    },
    optionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 2,
    },
    optionSubtitle: {
      fontSize: 14,
      color: theme.textSecondary,
      lineHeight: 20,
    },
  });

/**
 * Mobile-specific styles for Teacher Dashboard
 * Used when screen width < 768px
 */
export const getMobileStyles = (theme: any, isDark: boolean) =>
  StyleSheet.create({
    header: {
      backgroundColor: 'transparent',
      padding: 12,
      paddingTop: 8,
    },
    headerCard: {
      backgroundColor: theme.cardBackground,
      borderRadius: 12,
      padding: 12,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    headerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 2,
    },
    subRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexWrap: 'wrap',
    },
    roleBadge: {
      backgroundColor: theme.primary + '10',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 999,
    },
    roleBadgeText: {
      color: theme.primary,
      fontSize: 9,
      fontWeight: '600',
      textTransform: 'capitalize',
    },
    greeting: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.text,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    themeToggleButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.primary + '12',
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerMenuButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.textSecondary + '10',
      alignItems: 'center',
      justifyContent: 'center',
    },
    hamburgerButton: {
      width: 36,
      height: 36,
      borderRadius: 8,
      backgroundColor: theme.textSecondary + '10',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
  });