/**
 * Teacher Dashboard Styles — extracted from NewEnhancedTeacherDashboard.tsx
 *
 * Keeps the main component file focused on logic and JSX.
 */

import { StyleSheet } from 'react-native';

export type LayoutMetrics = {
  isTablet: boolean;
  isSmallScreen: boolean;
  cardPadding: number;
  cardGap: number;
};

export const getLayoutMetrics = (width: number): LayoutMetrics => {
  const isTablet = width > 768;
  const isSmallScreen = width < 380;
  const cardPadding = isTablet ? 22 : isSmallScreen ? 12 : 16;
  const cardGap = isTablet ? 14 : isSmallScreen ? 8 : 10;
  return { isTablet, isSmallScreen, cardPadding, cardGap };
};

const GLASS_BG = 'rgba(255,255,255,0.05)';
const GLASS_BG_VARIANT = 'rgba(255,255,255,0.07)';
const GLASS_BORDER = 'rgba(255,255,255,0.10)';
const GLASS_BORDER_LIGHT = 'rgba(255,255,255,0.08)';
const GLASS_DIVIDER = 'rgba(255,255,255,0.06)';

export const createTeacherDashboardStyles = (
  theme: any,
  _topInset: number,
  _bottomInset: number,
  layout: LayoutMetrics,
) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#0F121E',
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingTop: 24,
      paddingHorizontal: layout.cardPadding,
      paddingBottom: 42,
      gap: 18,
      width: '100%',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#0F121E',
    },
    loadingText: {
      fontSize: 16,
      color: 'rgba(234,240,255,0.72)',
      marginTop: 14,
    },
    emptyText: {
      fontSize: 13,
      color: 'rgba(234,240,255,0.72)',
      marginTop: 10,
    },
    headerCard: {
      borderRadius: 20,
      overflow: 'hidden',
      backgroundColor: GLASS_BG,
      borderWidth: 1,
      borderColor: GLASS_BORDER,
      shadowColor: '#000',
      shadowOpacity: 0.35,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 14 },
      elevation: 10,
    },
    headerGradient: {
      paddingHorizontal: layout.isTablet ? 24 : 18,
      paddingVertical: layout.isTablet ? 24 : 20,
    },
    headerContent: {
      gap: 18,
    },
    greetingTextContainer: {
      gap: 6,
    },
    greeting: {
      fontSize: layout.isTablet ? 30 : layout.isSmallScreen ? 22 : 26,
      fontWeight: '700',
      color: '#EAF0FF',
    },
    subtitle: {
      fontSize: layout.isTablet ? 16 : 14,
      color: 'rgba(234,240,255,0.82)',
      fontWeight: '500',
      lineHeight: 20,
    },
    heroSummaryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.16)',
      backgroundColor: 'rgba(15,18,30,0.28)',
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 14,
    },
    heroMetricPrimary: {
      minWidth: 110,
    },
    heroMetricPrimaryValue: {
      fontSize: layout.isTablet ? 40 : 34,
      fontWeight: '700',
      color: '#EAF0FF',
      lineHeight: layout.isTablet ? 42 : 36,
    },
    heroMetricPrimaryLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: 'rgba(234,240,255,0.72)',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginTop: 2,
    },
    heroMetricDivider: {
      width: 1,
      alignSelf: 'stretch',
      backgroundColor: 'rgba(255,255,255,0.18)',
    },
    heroMetricStack: {
      flex: 1,
      gap: 6,
      justifyContent: 'center',
    },
    heroGrowthText: {
      fontSize: 20,
      fontWeight: '700',
      color: '#3C8E62',
    },
    heroAttendanceText: {
      fontSize: 13,
      color: 'rgba(234,240,255,0.72)',
      fontWeight: '600',
    },
    schoolCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 14,
      padding: 12,
      gap: 12,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.16)',
      backgroundColor: 'rgba(15,18,30,0.24)',
    },
    schoolIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: 'rgba(255,255,255,0.12)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    schoolIcon: {
      fontSize: 20,
    },
    schoolTextContainer: {
      flex: 1,
    },
    schoolLabel: {
      fontSize: 11,
      color: 'rgba(234,240,255,0.72)',
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 2,
    },
    schoolName: {
      fontSize: layout.isTablet ? 16 : 14,
      color: '#EAF0FF',
      fontWeight: '700',
    },
    standaloneCard: {
      borderRadius: 18,
      padding: 14,
      backgroundColor: GLASS_BG,
      borderWidth: 1,
      borderColor: GLASS_BORDER,
      shadowColor: '#000',
      shadowOpacity: 0.35,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 14 },
      elevation: 10,
      gap: 12,
    },
    standaloneHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    standaloneIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(90, 64, 157, 0.2)',
      borderWidth: 1,
      borderColor: GLASS_BORDER_LIGHT,
    },
    standaloneTitle: {
      color: '#EAF0FF',
      fontSize: 15,
      fontWeight: '700',
      flex: 1,
    },
    standaloneDescription: {
      color: 'rgba(234,240,255,0.78)',
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '500',
    },
    standaloneActionsRow: {
      flexDirection: 'row',
      gap: 10,
      flexWrap: 'wrap',
    },
    standalonePrimaryButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minHeight: 42,
      borderRadius: 12,
      paddingHorizontal: 12,
      backgroundColor: '#5A409D',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
    },
    standalonePrimaryButtonText: {
      color: '#EAF0FF',
      fontSize: 12,
      fontWeight: '700',
    },
    standaloneSecondaryButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minHeight: 42,
      borderRadius: 12,
      paddingHorizontal: 12,
      backgroundColor: 'rgba(255,255,255,0.04)',
      borderWidth: 1,
      borderColor: GLASS_BORDER_LIGHT,
    },
    standaloneSecondaryButtonText: {
      color: '#EAF0FF',
      fontSize: 12,
      fontWeight: '700',
    },
    tierBadge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
    },
    tierBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: '#FFFFFF',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    highlightsSection: {
      gap: 10,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      marginBottom: 2,
    },
    sectionHeaderTitle: {
      fontSize: layout.isTablet ? 20 : 18,
      fontWeight: '700',
      color: '#EAF0FF',
    },
    sectionHeaderHint: {
      fontSize: 12,
      color: 'rgba(234,240,255,0.72)',
    },
    highlightsRow: {
      paddingHorizontal: 2,
      paddingBottom: 2,
    },
    highlightCard: {
      minWidth: layout.isSmallScreen ? 160 : 196,
      borderRadius: 18,
      padding: 14,
      marginRight: 12,
      backgroundColor: GLASS_BG,
      borderWidth: 1,
      borderColor: GLASS_BORDER,
      shadowColor: '#000',
      shadowOpacity: 0.35,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 14 },
      elevation: 10,
    },
    highlightIcon: {
      width: 34,
      height: 34,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    highlightLabel: {
      fontSize: 10,
      color: 'rgba(234,240,255,0.72)',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      fontWeight: '600',
    },
    highlightValue: {
      fontSize: layout.isTablet ? 22 : 19,
      fontWeight: '700',
      color: '#EAF0FF',
      marginTop: 4,
    },
    highlightSub: {
      fontSize: 12,
      color: 'rgba(234,240,255,0.72)',
      marginTop: 3,
    },
    tutorModeCard: {
      borderRadius: 20,
      overflow: 'hidden',
      backgroundColor: GLASS_BG,
      borderWidth: 1,
      borderColor: GLASS_BORDER,
      shadowColor: '#000',
      shadowOpacity: 0.45,
      shadowRadius: 26,
      shadowOffset: { width: 0, height: 15 },
      elevation: 11,
    },
    tutorModeGradient: {
      paddingHorizontal: 18,
      paddingVertical: 16,
      gap: 8,
    },
    tutorModeTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 2,
    },
    tutorModeBadge: {
      color: '#EAF0FF',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    tutorModeTitle: {
      fontSize: layout.isTablet ? 22 : 18,
      lineHeight: layout.isTablet ? 28 : 24,
      color: '#EAF0FF',
      fontWeight: '700',
    },
    tutorModeDescription: {
      fontSize: 13,
      lineHeight: 18,
      color: 'rgba(234,240,255,0.82)',
      marginBottom: 6,
    },
    tutorModeButton: {
      alignSelf: 'flex-start',
      backgroundColor: '#5A409D',
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      minHeight: 44,
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOpacity: 0.3,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 8,
    },
    tutorModeButtonText: {
      color: '#EAF0FF',
      fontSize: 13,
      fontWeight: '700',
    },
    routineCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: GLASS_BORDER,
      backgroundColor: GLASS_BG,
      paddingHorizontal: 14,
      paddingVertical: 14,
      gap: 8,
      shadowColor: '#000',
      shadowOpacity: 0.35,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 14 },
      elevation: 10,
    },
    routineTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    routineBadge: {
      color: '#EAF0FF',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    routineTitle: {
      color: '#EAF0FF',
      fontSize: 18,
      fontWeight: '700',
    },
    routineDescription: {
      color: 'rgba(234,240,255,0.82)',
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '500',
    },
    routineActionsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 8,
      marginTop: 2,
    },
    routinePrimaryButton: {
      flex: 1,
      minHeight: 42,
      borderRadius: 12,
      backgroundColor: '#3A7CA5',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.16)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    routinePrimaryButtonText: {
      color: '#EAF0FF',
      fontSize: 12,
      fontWeight: '700',
    },
    routineSecondaryButton: {
      flex: 1,
      minHeight: 42,
      borderRadius: 12,
      backgroundColor: 'rgba(255,255,255,0.08)',
      borderWidth: 1,
      borderColor: GLASS_BORDER_LIGHT,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    routineSecondaryButtonDisabled: {
      opacity: 0.5,
    },
    routineSecondaryButtonText: {
      color: '#EAF0FF',
      fontSize: 12,
      fontWeight: '700',
    },
    routineMeta: {
      color: 'rgba(234,240,255,0.70)',
      fontSize: 11,
      fontWeight: '600',
    },
    routineStatusText: {
      color: '#86EFAC',
      fontSize: 11,
      fontWeight: '700',
    },
    actionSection: {
      marginBottom: 16,
    },
    actionSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 10,
    },
    actionSectionIcon: {
      width: 24,
      height: 24,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: GLASS_BG_VARIANT,
      borderWidth: 1,
      borderColor: GLASS_BORDER_LIGHT,
    },
    actionSectionTitle: {
      fontSize: 13,
      color: 'rgba(234,240,255,0.72)',
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    metricsGrid: {
      width: '100%',
      gap: layout.cardGap,
    },
    metricRow: {
      flexDirection: 'row',
      width: '100%',
      gap: layout.cardGap,
      marginBottom: layout.cardGap,
    },
    metricRowLast: {
      marginBottom: 0,
    },
    actionsGrid: {
      width: '100%',
      gap: layout.cardGap,
    },
    actionRow: {
      flexDirection: 'row',
      width: '100%',
      gap: layout.cardGap,
      marginBottom: layout.cardGap,
    },
    actionRowLast: {
      marginBottom: 0,
    },
    classOverviewRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: GLASS_BORDER,
      backgroundColor: GLASS_BG,
      padding: 12,
      marginBottom: 10,
      shadowColor: '#000',
      shadowOpacity: 0.35,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 14 },
      elevation: 10,
    },
    classOverviewRowLast: {
      marginBottom: 0,
    },
    classOverviewIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
      backgroundColor: 'rgba(90, 64, 157, 0.2)',
      borderWidth: 1,
      borderColor: GLASS_BORDER_LIGHT,
    },
    classOverviewContent: {
      flex: 1,
      gap: 3,
    },
    classOverviewTitle: {
      color: '#EAF0FF',
      fontSize: 15,
      fontWeight: '700',
    },
    classOverviewSubtitle: {
      color: 'rgba(234,240,255,0.72)',
      fontSize: 12,
      fontWeight: '500',
    },
    classOverviewMetrics: {
      alignItems: 'flex-end',
      gap: 2,
    },
    classOverviewAttendance: {
      color: '#3C8E62',
      fontSize: 20,
      fontWeight: '700',
    },
    classOverviewAttendanceLabel: {
      color: 'rgba(234,240,255,0.72)',
      fontSize: 11,
      fontWeight: '600',
    },
    assignmentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: GLASS_DIVIDER,
    },
    assignmentRowLast: {
      borderBottomWidth: 0,
      paddingBottom: 4,
    },
    assignmentIconContainer: {
      width: 36,
      height: 36,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: GLASS_BORDER_LIGHT,
    },
    assignmentInfo: {
      flex: 1,
      gap: 2,
    },
    assignmentTitle: {
      color: '#EAF0FF',
      fontSize: 14,
      fontWeight: '700',
    },
    assignmentSubTitle: {
      color: 'rgba(234,240,255,0.72)',
      fontSize: 12,
      fontWeight: '500',
    },
    assignmentStatus: {
      color: 'rgba(234,240,255,0.72)',
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    assignmentStatusSuccess: {
      color: '#3C8E62',
    },
    assignmentStatusWarning: {
      color: theme.warning || '#F59E0B',
    },
    recentActivityPanel: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: GLASS_BORDER,
      borderTopColor: 'rgba(255,255,255,0.06)',
      backgroundColor: GLASS_BG,
      paddingHorizontal: 12,
      paddingVertical: 8,
      shadowColor: '#000',
      shadowOpacity: 0.35,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 14 },
      elevation: 10,
    },
    recentActivityRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: GLASS_DIVIDER,
      gap: 10,
    },
    recentActivityRowLast: {
      borderBottomWidth: 0,
    },
    recentActivityIcon: {
      width: 34,
      height: 34,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: GLASS_BORDER_LIGHT,
    },
    recentActivityContent: {
      flex: 1,
      gap: 2,
    },
    recentActivityTitle: {
      color: '#EAF0FF',
      fontSize: 14,
      fontWeight: '700',
    },
    recentActivitySubtitle: {
      color: 'rgba(234,240,255,0.72)',
      fontSize: 12,
      fontWeight: '500',
    },
    recentActivityTimestamp: {
      color: 'rgba(234,240,255,0.72)',
      fontSize: 11,
      fontWeight: '600',
      maxWidth: 84,
      textAlign: 'right',
    },
    retryButton: {
      marginTop: 16,
      paddingHorizontal: 24,
      paddingVertical: 10,
      borderRadius: 8,
    },
    retryButtonText: {
      color: '#FFFFFF',
      fontWeight: '600',
      fontSize: 14,
    },
  });
