/**
 * Styles for PayrollPaymentHistory component
 */

import { StyleSheet } from 'react-native';

export const createPayrollHistoryStyles = (theme: any) =>
  StyleSheet.create({
    keyboardAvoid: { flex: 1 },
    overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
    card: {
      backgroundColor: theme.cardBackground,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      padding: 16,
      maxHeight: '85%',
      borderTopWidth: 1,
      borderColor: theme.border,
    },
    header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
    title: { fontSize: 18, fontWeight: '800', color: theme.text },
    subtitle: { fontSize: 13, color: theme.textSecondary, marginTop: 2 },
    summaryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      backgroundColor: theme.primary + '12',
      borderRadius: 10,
      marginBottom: 12,
    },
    summaryLabel: { fontSize: 13, color: theme.textSecondary, fontWeight: '600' },
    summaryValue: { fontSize: 16, fontWeight: '800', color: theme.text },
    summaryCount: { fontSize: 12, color: theme.textSecondary, marginLeft: 'auto' },
    scroll: { flexShrink: 1 },
    center: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40 },
    emptyText: { color: theme.textSecondary, marginTop: 12, fontSize: 14 },
    paymentCard: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      padding: 12,
      marginBottom: 10,
      backgroundColor: theme.surface,
    },
    voidedCard: { opacity: 0.6, borderStyle: 'dashed' as any },
    paymentHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    paymentAmount: { fontSize: 16, fontWeight: '700', color: theme.text },
    voidedText: { textDecorationLine: 'line-through', color: theme.textSecondary },
    statusBadge: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
    statusText: { fontSize: 10, fontWeight: '700' },
    paymentMeta: { fontSize: 12, color: theme.textSecondary, marginTop: 3 },
    editNote: { fontSize: 12, color: '#F59E0B', marginTop: 4, fontStyle: 'italic' },
    voidNote: { fontSize: 12, color: '#EF4444', marginTop: 4, fontStyle: 'italic' },
    actionRow: { flexDirection: 'row', gap: 16, marginTop: 10 },
    editBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    voidBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    actionText: { fontSize: 13, fontWeight: '600' },
    innerModal: {
      backgroundColor: theme.cardBackground,
      marginHorizontal: 16,
      marginVertical: 'auto',
      borderRadius: 16,
      padding: 20,
      borderWidth: 1,
      borderColor: theme.border,
    },
    inputLabel: { fontSize: 12, fontWeight: '700', color: theme.textSecondary, marginTop: 12 },
    input: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: theme.text,
      backgroundColor: theme.surface,
      fontSize: 14,
      marginTop: 4,
    },
    btnRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 16 },
    cancelBtn: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
      paddingHorizontal: 16,
      paddingVertical: 9,
    },
    cancelText: { color: theme.text, fontWeight: '700', fontSize: 13 },
    confirmBtn: {
      backgroundColor: theme.primary,
      borderRadius: 10,
      paddingHorizontal: 16,
      paddingVertical: 9,
      alignItems: 'center',
      justifyContent: 'center',
    },
    confirmText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  });
