/**
 * Styles for the sign-in screen.
 * Extracted from sign-in.tsx to comply with WARP.md.
 *
 * @module features/auth/sign-in.styles
 */

import { StyleSheet, Platform } from 'react-native';
import { marketingTokens } from '@/components/marketing/tokens';

export function createSignInStyles(theme: any, insets: { top: number; bottom: number }) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
      ...(Platform.OS === 'web' && {
        minHeight: '100%' as any,
        justifyContent: 'center' as const,
        alignItems: 'center' as const,
      }),
    },
    keyboardView: {
      flex: 1,
      ...(Platform.OS === 'web' && {
        width: '100%',
        maxWidth: '100%',
        alignSelf: 'center' as const,
      }),
    },
    logoContainer: {
      alignItems: 'center' as const,
      marginBottom: 24,
      paddingTop: 20,
      ...(Platform.OS === 'web' && { paddingTop: 0 }),
    },
    logoCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: theme.surfaceVariant,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      marginBottom: 12,
      borderWidth: 2,
      borderColor: theme.border,
    },
    logoText: {
      fontSize: 24,
      fontWeight: '800' as const,
      color: theme.text,
      marginBottom: 4,
    },
    logoSubtext: {
      fontSize: 13,
      color: theme.textSecondary,
      fontWeight: '500' as const,
    },
    scrollView: {
      flex: 1,
      ...(Platform.OS === 'web' && { width: '100%' }),
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: Platform.OS === 'ios' ? 20 : 40,
      ...(Platform.OS === 'web' && {
        minHeight: '100%' as any,
        justifyContent: 'center' as const,
        paddingVertical: 40,
      }),
    },
    content: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 20,
      justifyContent: 'center' as const,
      width: '100%',
      ...(Platform.OS === 'web' && {
        flex: 0,
        paddingVertical: 0,
        paddingHorizontal: 40,
      }),
    },
    card: {
      width: '100%',
      alignSelf: 'center' as const,
      ...(Platform.OS === 'web' && { marginVertical: 20, maxWidth: '100%' }),
    },
    header: {
      marginBottom: 20,
      alignItems: 'center' as const,
      gap: 4,
    },
    title: {
      fontSize: 22,
      fontWeight: '800' as const,
      color: marketingTokens.colors.fg.primary,
      textAlign: 'center' as const,
    },
    subtitle: {
      fontSize: 13,
      color: marketingTokens.colors.fg.secondary,
      textAlign: 'center' as const,
    },
    biometricLoadingContainer: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      marginTop: 16,
      padding: 12,
      backgroundColor: theme.surfaceVariant,
      borderRadius: 8,
      gap: 12,
    },
    biometricLoadingText: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    form: {
      marginTop: 16,
      gap: 12,
    },
    input: {
      borderWidth: 1,
      borderColor: theme.inputBorder,
      borderRadius: 10,
      padding: 14,
      color: theme.inputText,
      backgroundColor: theme.inputBackground,
    },
    button: {
      flex: 1,
      backgroundColor: theme.primary,
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: 'center' as const,
    },
    buttonText: {
      color: theme.onPrimary,
      fontSize: 16,
      fontWeight: '700' as const,
    },
    buttonDisabled: {
      backgroundColor: theme.textSecondary,
    },
    passwordContainer: {
      position: 'relative' as const,
    },
    passwordInput: {
      paddingRight: 48,
    },
    eyeButton: {
      position: 'absolute' as const,
      right: 12,
      top: 14,
      padding: 4,
    },
    rememberForgotContainer: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
      marginTop: 8,
      marginBottom: 4,
    },
    rememberMeContainer: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
    },
    checkbox: {
      width: 20,
      height: 20,
      borderRadius: 4,
      borderWidth: 2,
      borderColor: theme.border,
      marginRight: 10,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      backgroundColor: theme.inputBackground,
    },
    checkboxChecked: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    rememberMeText: {
      fontSize: 14,
      color: theme.text,
    },
    forgotPasswordText: {
      fontSize: 14,
      color: marketingTokens.colors.accent.cyan400,
      fontWeight: '600' as const,
    },
    magicLinkButton: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: 8,
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: 'rgba(14, 165, 233, 0.08)',
      borderRadius: 10,
      borderWidth: 1,
      borderColor: 'rgba(14, 165, 233, 0.2)',
      marginTop: 4,
    },
    magicLinkText: {
      fontSize: 14,
      color: marketingTokens.colors.accent.cyan400,
      fontWeight: '500' as const,
    },
    dividerContainer: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      width: '100%',
      marginVertical: 8,
    },
    dividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: theme.border,
    },
    dividerText: {
      fontSize: 12,
      color: theme.textSecondary,
      marginHorizontal: 12,
    },
    signupPrompt: {
      marginTop: 20,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    divider: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      marginBottom: 12,
    },
    signupButton: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: 8,
      marginTop: 12,
      paddingVertical: 16,
      paddingHorizontal: 16,
      backgroundColor: 'rgba(99, 102, 241, 0.1)',
      borderRadius: 12,
      borderWidth: 2,
      borderColor: 'rgba(99, 102, 241, 0.3)',
      minHeight: 56,
    },
    signupButtonText: {
      fontSize: 15,
      fontWeight: '700' as const,
      color: marketingTokens.colors.fg.primary,
    },
    schoolSignupLink: {
      alignItems: 'center' as const,
      padding: 14,
      marginTop: 4,
    },
    schoolSignupText: {
      fontSize: 14,
      color: marketingTokens.colors.fg.secondary,
      textAlign: 'center' as const,
      lineHeight: 20,
    },
    schoolSignupLinkText: {
      color: marketingTokens.colors.accent.cyan400,
      fontWeight: '700' as const,
      textDecorationLine: 'underline' as const,
    },
    googleButton: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: 12,
      paddingVertical: 14,
      paddingHorizontal: 16,
      backgroundColor: '#4285F4',
      borderRadius: 10,
      minHeight: 48,
      marginTop: 8,
    },
    googleButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600' as const,
    },
    homeButtonContainer: {
      position: 'absolute' as const,
      top: Platform.OS === 'web' ? 16 : Math.max(insets.top + 8, 16),
      right: 16,
      zIndex: 10,
    },
    homeButton: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: 'rgba(14, 165, 233, 0.1)',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(14, 165, 233, 0.3)',
      minHeight: 44,
      minWidth: 44,
    },
    homeButtonText: {
      color: marketingTokens.colors.accent.cyan400,
      fontSize: 14,
      fontWeight: '600' as const,
    },
    signInLoadingBanner: {
      position: 'absolute' as const,
      left: 16,
      right: 16,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 12,
      backgroundColor: theme.surfaceVariant,
      borderWidth: 1,
      borderColor: theme.border,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 10,
      shadowColor: '#000',
      shadowOpacity: 0.2,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 6,
    },
    signInLoadingText: {
      color: theme.textSecondary,
      fontSize: 13,
      fontWeight: '600' as const,
      flex: 1,
    },
  });
}
