-- Seed system-wide activity samples for Literacy, Numeracy, Life Skills
-- These are browsable by teachers and principals

INSERT INTO activity_sample_library (
  preschool_id,
  strand,
  title,
  description,
  age_group,
  duration_minutes,
  objectives,
  materials,
  instructions,
  caps_alignment,
  is_system_template
) VALUES
-- Literacy
(NULL, 'literacy', 'Letter Sound Match', 'Match letters to pictures that start with that sound', '4-5', 15,
 '["Phonemic awareness", "Letter-sound correspondence"]'::jsonb,
 '["Picture cards", "Letter cards"]'::jsonb,
 'Display a letter card. Ask learners to find a picture that starts with that sound. Extend by having them say the word.',
 'CAPS Home Language: Phonics',
 true),
(NULL, 'literacy', 'Story Retell', 'Retell a familiar story in sequence', '4-6', 20,
 '["Listening comprehension", "Sequencing", "Oral language"]'::jsonb,
 '["Story book", "Picture sequence cards"]'::jsonb,
 'Read a short story. Use picture cards for learners to order events. Invite learners to retell in their own words.',
 'CAPS Home Language: Comprehension',
 true),
(NULL, 'literacy', 'Rhyme Time', 'Identify and produce rhyming words', '3-5', 10,
 '["Phonological awareness", "Rhyme recognition"]'::jsonb,
 '["Rhyme cards", "Pictures"]'::jsonb,
 'Show picture pairs. Ask: Do these rhyme? Extend: What rhymes with cat?',
 'CAPS Home Language: Phonological awareness',
 true),
-- Numeracy
(NULL, 'numeracy', 'Count and Match', 'Count objects and match to numerals', '3-5', 15,
 '["One-to-one correspondence", "Number recognition"]'::jsonb,
 '["Counters", "Number cards 1-10"]'::jsonb,
 'Give learners counters. Ask them to count and find the matching number card.',
 'CAPS Mathematics: Number concept',
 true),
(NULL, 'numeracy', 'Shapes Hunt', 'Identify and name 2D shapes in the environment', '4-5', 15,
 '["Shape recognition", "Spatial awareness"]'::jsonb,
 '["Shape flashcards", "Real objects"]'::jsonb,
 'Show a shape. Learners find objects with that shape in the room. Name and describe.',
 'CAPS Mathematics: Space and shape',
 true),
(NULL, 'numeracy', 'Pattern Making', 'Create and extend simple patterns', '4-6', 15,
 '["Pattern recognition", "Logical thinking"]'::jsonb,
 '["Coloured blocks", "Beads", "Picture cards"]'::jsonb,
 'Start a pattern (e.g. red-blue-red). Ask: What comes next? Learners extend.',
 'CAPS Mathematics: Patterns',
 true),
-- Life Skills
(NULL, 'life_skills', 'Weather Circle', 'Discuss daily weather and appropriate clothing', '3-5', 10,
 '["Weather awareness", "Vocabulary", "Self-care"]'::jsonb,
 '["Weather chart", "Clothing pictures"]'::jsonb,
 'Check the weather together. Discuss what to wear. Link to seasons.',
 'CAPS Life Skills: Beginning knowledge',
 true),
(NULL, 'life_skills', 'Handwashing Routine', 'Practice correct handwashing steps', '3-6', 10,
 '["Hygiene", "Sequencing", "Self-help"]'::jsonb,
 '["Soap", "Towel", "Poster"]'::jsonb,
 'Model and practise: wet, soap, scrub, rinse, dry. Use a song or rhyme.',
 'CAPS Life Skills: Personal care',
 true),
(NULL, 'life_skills', 'Sharing and Taking Turns', 'Role-play sharing and turn-taking', '3-5', 15,
 '["Social skills", "Emotional regulation"]'::jsonb,
 '["Toys", "Timer"]'::jsonb,
 'Set up a sharing scenario. Use a timer for turns. Discuss how it feels to share.',
 'CAPS Life Skills: Social development',
 true);
