-- =============================================================================
-- Fix Principal Dashboard RLS Policies
-- =============================================================================
-- Issues fixed:
-- 1. pdf_documents: only user_id = auth.uid() — principals can't see
--    receipts/invoices generated by other staff at the same school
-- 2. school_branding: WITH CHECK excludes principal_admin role
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Add tenant-level SELECT on pdf_documents so principals can view
--    all receipts/invoices/PDFs for their school
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "pdf_documents_tenant_select" ON public.pdf_documents;

CREATE POLICY "pdf_documents_tenant_select"
ON public.pdf_documents
FOR SELECT
TO authenticated
USING (
    -- Own documents always visible
    user_id = auth.uid()
    OR
    -- Principals/admins can see all documents for their school
    (
        COALESCE(preschool_id, organization_id) IN (
            SELECT COALESCE(p.organization_id, p.preschool_id)
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN (
                  'principal',
                  'principal_admin',
                  'admin',
                  'super_admin'
              )
        )
    )
);


-- ---------------------------------------------------------------------------
-- 2. Update school_branding WITH CHECK to include principal_admin
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "school_branding_tenant_modify" ON public.school_branding;

CREATE POLICY "school_branding_tenant_modify"
ON public.school_branding
AS PERMISSIVE
FOR ALL
TO authenticated
USING (
    preschool_id IN (
        SELECT profiles.organization_id
        FROM public.profiles
        WHERE profiles.id = auth.uid()
    )
)
WITH CHECK (
    preschool_id IN (
        SELECT profiles.organization_id
        FROM public.profiles
        WHERE profiles.id = auth.uid()
          AND profiles.role IN (
              'teacher',
              'admin',
              'principal',
              'principal_admin',
              'super_admin'
          )
    )
);
